-- ============================================================================ 
-- CUSTOMER_SHOPPING_BEHAVIOR_SQL_PROJECT (PostgreSQL) — End-to-End Project
-- Compatible with PostgreSQL4 - Run section-by-section or all.
-- ============================================================================

/* ---------------------------------------------------------------------------
   0) SAFETY SETUP
--------------------------------------------------------------------------- */

DROP TABLE IF EXISTS customer_behavior;

/* ---------------------------------------------------------------------------
   1) CUSTOMER_SHOPPING_BEHAVIOR TABLES
------------------------------------------------------------------------------ 
*/ 
CREATE TABLE customer_behavior (
    customer_id INT PRIMARY KEY,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(50),
    purchase_amount_usd INT,
    location VARCHAR(100),
    size VARCHAR(10),
    color VARCHAR(50),
    season VARCHAR(20),
    review_rating FLOAT,
    subscription_status VARCHAR(10),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    promo_code_used VARCHAR(10),
    previous_purchases INT,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50)
);

SELECT * FROM customer_behavior;


-- ======================== 
-- 1 - DATA EXPLORATION 
-- ========================

-- Count of Rows. 
SELECT COUNT(*) FROM customer_behavior;

-- Sample Data 
SELECT * FROM customer_behavior 
LIMIT 10;

-- Null Values 
SELECT * FROM customer_behavior 
WHERE age IS NULL 
OR 
gender IS NULL 
OR 
item_purchased IS NULL 
OR 
category IS NULL 
OR 
purchase_amount_usd IS NULL 
OR 
location IS NULL 
OR 
size IS NULL 
OR 
color IS NULL 
OR 
season IS NULL 
OR 
review_rating IS NULL 
OR 
subscription_status IS NULL
OR 
shipping_type IS NULL
OR 
discount_applied IS NULL
OR 
promo_code_used IS NULL
OR 
previous_purchases IS NULL
OR 
payment_method IS NULL
OR 
frequency_of_purchases IS NULL; 

-- Count Null Values 
SELECT COUNT(*) FROM customer_behavior 
WHERE age IS NULL 
OR 
gender IS NULL 
OR 
item_purchased IS NULL 
OR 
category IS NULL 
OR 
purchase_amount_usd IS NULL 
OR 
location IS NULL 
OR 
size IS NULL 
OR 
color IS NULL 
OR 
season IS NULL 
OR 
review_rating IS NULL 
OR 
subscription_status IS NULL
OR 
shipping_type IS NULL
OR 
discount_applied IS NULL
OR 
promo_code_used IS NULL
OR 
previous_purchases IS NULL
OR 
payment_method IS NULL
OR 
frequency_of_purchases IS NULL; 

-- ======================== 
-- 2 - DATA ANALYSIS 
-- ========================

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd) AS Total_revenue
FROM customer_behavior 
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount_usd 
FROM customer_behavior 
WHERE discount_applied = 'Yes' AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer_behavior);  

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, review_rating 
FROM customer_behavior 
WHERE review_rating > (SELECT AVG(review_rating) AS Avg_rating FROM customer_behavior) 
LIMIT 5; 

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount_usd), 2)  
FROM customer_behavior 
WHERE shipping_type IN ('Express' , 'Standard')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
	-- between subscribers and non-subscribers.
SELECT subscription_status, 
	COUNT(customer_id) AS Total_customers, 
	ROUND(AVG(purchase_amount_usd), 2) AS Avg_spend, 
    SUM(purchase_amount_usd) AS Total_revenue 
FROM customer_behavior 
GROUP BY subscription_status 
ORDER BY Total_revenue, Avg_spend DESC; 

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
    CAST(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::DECIMAL / COUNT(*) AS DECIMAL(10,2)) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
	-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS ( 
SELECT customer_id, previous_purchases, 
CASE 
	WHEN previous_purchases = 1 THEN 'New' 
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' 
    ELSE 'Loyal' 
    END AS customer_segment 
FROM customer_behavior 
) 

SELECT customer_segment, COUNT(*) AS Number_of_Customers 
FROM customer_type 
GROUP BY customer_segment; 

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS ( 
SELECT category, 
		item_purchased, 
        COUNT(customer_id) AS Total_orders, 
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS Item_rank  
        FROM customer_behavior 
        GROUP BY category, item_purchased 
        ) 
SELECT category, item_purchased, Total_orders, Item_rank 
FROM Item_counts 
WHERE Item_rank <= 3; 

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, 
	COUNT(customer_id) AS Repeat_buyers 
FROM customer_behavior 
WHERE previous_purchases > 5 
GROUP BY subscription_status; 

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, 
	SUM(purchase_amount_usd) AS Total_revenue  
FROM customer_behavior 
GROUP BY age_group 
ORDER BY Total_revenue DESC;

SELECT * FROM customer_behavior;
